# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxtweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VqTestcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcno', models.CharField(db_column='TCNO', max_length=20)),
                ('interfacename', models.CharField(db_column='InterfaceName', max_length=32)),
                ('url', models.CharField(db_column='URL', max_length=40)),
                ('method', models.CharField(db_column='Method', max_length=15)),
                ('introduce', models.TextField(db_column='Introduce')),
                ('priorty', models.CharField(db_column='Priorty', max_length=10)),
                ('flag', models.IntegerField(db_column='Flag')),
                ('parameter', models.TextField(db_column='Parameter')),
                ('expected_result', models.CharField(db_column='Expected Result', max_length=50)),
                ('testresult', models.CharField(blank=True, db_column='TestResult', max_length=50, null=True)),
                ('comment', models.CharField(blank=True, db_column='Comment', max_length=50, null=True)),
                ('interfaceid', models.CharField(blank=True, db_column='interfaceId', max_length=200, null=True)),
            ],
            options={
                'db_table': 'vq_testcase',
                'managed': False,
            },
        ),
    ]
